<?php

/**
 * @file
 * Provides a dictionary test entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function dictionary_test_theme() {
  return [
    'dictionary_test' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for dictionary test templates.
 *
 * Default template: dictionary-test.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the dictionary test information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_dictionary_test(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
